name: Build and publish to GitHub registry

permissions:
  contents: read
  packages: write

on:
  push:
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONNECTIQ_SDK_VERSION:
          - 7.2.1
          - 7.1.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-sdk-v${{ matrix.CONNECTIQ_SDK_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args:
            SDK_VERSION: ${{ matrix.CONNECTIQ_SDK_VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #tags: ${{ github.repository }}-sdk-v${{ matrix.CONNECTIQ_SDK_VERSION }}
          labels: SDK-${{ matrix.CONNECTIQ_SDK_VERSION }}
